config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]

  resources :subs, except: :destroy

  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true

  belongs_to :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id,
    inverse_of: :posts

  has_many :post_subs,
    class_name: "PostSub",
    foreign_key: :post_id,
    primary_key: :id,
    inverse_of: :post

  has_many :subs, through: :post_subs, source: :sub

end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  #validates :post_id, presence: true  #:sub_id,
  validates :post_id, uniqueness: { scope: :sub_id }

  belongs_to :post,
    class_name: "Post",
    foreign_key: :post_id,
    primary_key: :id,
    inverse_of: :post_subs

  belongs_to :sub,
    class_name: "Sub",
    foreign_key: :sub_id,
    primary_key: :id,
    inverse_of: :post_subs
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id,
    inverse_of: :subs

  has_many :post_subs,
    class_name: "PostSub",
    foreign_key: :sub_id,
    primary_key: :id,
    dependent: :destroy,
    inverse_of: :sub

  has_many :posts, through: :post_subs, source: :post
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, :password_digest, presence: true
  validates :email, :session_token, uniqueness: true

  after_initialize :ensure_session_token

  has_many :subs,
    class_name: "Sub",
    foreign_key: :moderator_id,
    primary_key: :id,
    inverse_of: :moderator

  has_many :posts,
    class_name: "Post",
    foreign_key: :author_id,
    primary_key: :id,
    inverse_of: :author

  def self.generate_session_token(field)
    begin
      token = SecureRandom::urlsafe_base64(16)
    end until !self.exists?(field => token)
    token
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token(:session_token)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token(:session_token)
    self.save!
    self.session_token
  end

  def password=(reg_password)
    self.password_digest = BCrypt::Password.create(reg_password)
  end

  def is_password?(reg_password)
    BCrypt::Password.new(self.password_digest).is_password?(reg_password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
    #fail
  end

  def logged_in?
    !!current_user
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :redirect_if_not_owner, only: [:edit, :update]

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.sub_ids = params[:post_sub][:sub_id]
    if @post.save
      redirect_to post_url(@post)
    else
      #fail
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  # transaction do
#     if @post.save
#       sub_ids = params[:post_sub][:sub_id]
#       sub_ids.each do |sub_id|
#         PostSub.create!(post_id: @post.id, sub_id: sub_id)
#       end
#     end
#   end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      @post = Post.new(post_params) if @post.nil?
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def destroy
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :url,
                                 :author_id)
  end

  def is_owner?
    current_user.id == Post.find(params[:id]).author_id
  end

  def redirect_if_not_owner
    unless is_owner?
      flash[:errors] = ["You're not the author!"]
      redirect_to post_url(Post.find(params[:id]))
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # set something?
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email],
                                  params[:user][:password])
    unless @user.nil?
      log_in!(@user)
      redirect_to subs_url
    else
      flash[:errors] = ["Incorrect email or password!"]
      @user = User.new
      render :new
    end
  end

  def destroy

    log_out!
    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_filter :redirect_if_not_owner, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to subs_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to subs_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      @sub = Sub.new if @sub.nil?
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

  def is_owner?
    current_user.id == Sub.find(params[:id]).moderator_id
  end

  def redirect_if_not_owner
    unless is_owner?
      flash[:errors] = ["You're not the moderator!"]
      redirect_to sub_url(Sub.find(params[:id]))
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def authenticate
    <<-HTML.html_safe
    <input type="hidden"
           name="authenticity_token"
           value="#{form_authenticity_token}">
    HTML
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  <h4><%= current_user.email %>
  <form action="<%= session_url %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= authenticate %>
    <button>Log out</button></h4>
  </form>
<% end %>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<form action="<%= action %>" method="post">
  <% if @post.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= authenticate %>

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <br>

  <label>url:
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <br>

  <label for="post_content">Content</label>
  <textarea name="post[content]" id="post_content"
    ><%= @post.content %></textarea>
  <br>

  <p>
  <label>Subs to post in:</label><br>
  <input type="hidden" name="post_sub[sub_id][]" value="">
  <% Sub.all.each do |sub| %>
    <label>
    <input type="checkbox" name="post_sub[sub_id][]"
      value="<%= sub.id %>">
    <%= sub.title %></label>
    <br>
  <% end %>
  </p>

  <input type="hidden" name="post[author_id]"
         value="<%= current_user.id %>">

  <button><%= button_name %> Post</button>

</form>

app/views/posts/edit.html.erb
<h1>Edit Post: <%= @post.title %></h1>

<%= render partial: "form", locals: { action: post_url(@post),
    button_name: "Update"} %>

app/views/posts/new.html.erb
<h1>Create a new Post</h1>

<%= render partial: "form", locals: { action: posts_url,
    button_name: "Create"} %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h4><a href="@post.url"><%= @post.url %></a></h4>
<h2>Content: <%= @post.content %></h2>
<h2>Author: <%= @post.author.email %></h2>


<a href="<%= edit_post_url(@post) %>">Edit</a>

app/views/shared/_creds.html.erb
<form action="<%= action %>" method="post">
  <%= authenticate %>

  <label for="user_email">Email</label>
  <input type="text" name="user[email]"
         id="user_email" value="<%= @user.email %>">
  <br>

  <label>Password
    <input type="password" name="user[password]">
  </label>
  <br>

  <input type="submit"></input>
</form>

app/views/subs/_form.html.erb
<form action="<%= action %>" method="post">
  <% unless @sub.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= authenticate %>

  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <br>

  <label for="sub_description">Description</label>
  <textarea name="sub[description]" id="sub_description"
    ><%= @sub.description %></textarea>
  <br>

  <input type="hidden" name="sub[moderator_id]"
         value="<%= current_user.id %>">

  <button><%= button_name %> Sub</button>
</form>

app/views/subs/edit.html.erb
<h1>Edit sub, <%= @sub.title %></h1>

<% action = sub_url(@sub) %>

<%= render partial: "form", locals: { sub: @sub, action: action, button_name: "Update" } %>

<form action="<%= sub_url(@sub) %>" method="get">
  <%= authenticate %>
  <button>Cancel</button>
</form>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Moderator</th>
  </tr>
  <% @subs.each do |sub| %>
    <tr>
      <td><a href="<%= sub_url(sub) %>"><%= sub.title %></a></td>
      <td><%= sub.description %></td>
      <td><%= sub.moderator.email %></td>
      <td><a href="<%= edit_sub_url(sub) %>">Edit</a></td>
    </tr>
  <% end %>
</table>

<a href="<%= new_sub_url %>">Create a new Sub</a>

app/views/subs/new.html.erb
<h1>Create a new sub</h1>

<% action = subs_url %>
<% button_name = "Create" %>

<%= render partial: "form", locals: { sub: @sub, action: action, button_name: button_name } %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<h2>Description: <%= @sub.description %></h2>
<h2>Moderator: <%= @sub.moderator.email %></h2>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Author</th>
    <th>url</th>
  </tr>
  <% @sub.posts.each do |post| %>
    <tr>
      <td><a href="<%= post_url(post) %>"><%= post.title %></a></td>
      <td><%= post.content %></td>
      <td><%= post.author.email %></td>
      <td><%= post.url %></td>
      <td><a href="<%= edit_post_url(post) %>">Edit</a></td>
    </tr>
  <% end %>
</table>

<a href="<%= subs_url %>">&lt;&lt; All Subs</a>
<a href="<%= edit_sub_url(@sub) %>">Edit</a>

app/views/users/new.html.erb
<h1>Create an Account</h1>
<% action = users_url %>

<%= render "shared/creds", user: @user, action: action %>

<a href="<%= new_session_url %>">Log in</a>